spring:
 ######### mongodb ########
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Spider
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:  classpath:/static/
 ########### redis #########
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1 # 设置数据库索引为1 默认为0
    password: # 密码为空
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
